export const userData = [
  {
    name: "John Doe",
    id: "001",
    joinDate: "2020-01-15",
    role: "Software Engineer",
    status: "Active",
    experience: "4 years",
    address: "lane 1",
    department: "Development",
  },
  {
    name: "Jane Smith",
    id: "002",
    joinDate: "2019-07-20",
    role: "Product Manager",
    status: "Inactive",
    experience: "5 years",
    address: "lane 2",
    department: "Product Management",
  },
  {
    name: "Alice Johnson",
    id: "003",
    joinDate: "2020-03-10",
    role: "Data Analyst",
    status: "Active",
    experience: "3 years",
    address: "lane 3",
    department: "Product Management",
  },
  {
    name: "Bob Williams",
    id: "004",
    joinDate: "2018-11-05",
    role: "Sales Manager",
    status: "Probation",
    experience: "6 months",
    address: "lane 4",
    department: "Sales",
  },
  {
    name: "Eve Brown",
    id: "005",
    joinDate: "2021-02-28",
    role: "HR Specialist",
    status: "Inactive",
    experience: "2 years",
    address: "lane 5",
    department: "Human Resource",
  },
  {
    name: "Michael Lee",
    id: "006",
    joinDate: "2017-09-15",
    role: "Software Developer",
    status: "Active",
    experience: "7 years",
    address: "lane 6",
    department: "Development",
  },
  {
    name: "Sophia Clark",
    id: "007",
    joinDate: "2019-05-12",
    role: "Marketing Manager",
    status: "Active",
    experience: "3 years",
    address: "lane 7",
    department: "Marketing",
  },
  {
    name: "David Taylor",
    id: "008",
    joinDate: "2020-08-20",
    role: "Financial Analyst",
    status: "Inactive",
    experience: "1 year",
    address: "lane 8",
    department: "Finanace",
  },
  {
    name: "Olivia Anderson",
    id: "009",
    joinDate: "2018-04-25",
    role: "Operations Coordinator",
    status: "Active",
    experience: "4 years",
    address: "lane 9",
    department: "Project Management",
  },
  {
    name: "Liam Wilson",
    id: "010",
    joinDate: "2019-11-30",
    role: "Customer Support Specialist",
    status: "Active",
    experience: "2 years",
    address: "lane 10",
    department: "Customer Support",
  },
];
